name: Rockbell
favicon: null
layout_spectrum: 0.8261625112500042
typography_spectrum: 0.7867526265326887
title: Rockbell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2065413563977927
  lightness: 0.9110708963125944
  saturation: 0.4058523843996227
  rhythmicContrast: 0.5100143775343895
purpose: []
